#!/bin/sh

if [ ! -n "$1" ]; then
	echo "$0 <keymap.c file>"
	exit 1
fi

keyfile=$1


# For each combo def
cat "$keyfile" | grep "COMBO_END" |\
	while read combo; do
		name=$(echo "$combo" | awk '{print $4}' |\
		   	awk '{ print substr( $0, 1, length($0)-2 ) }')

		# Combo keys:
		echo "$combo" | sed 's/.*{//' | tr ',' '\n' |\
			while read key; do
				case "$key" in
					*COMBO_END*) break
					;;
					*) echo -n "$key, "
					;;
				esac
			done

		# Combo product:
		echo -n "= $(cat "$keyfile" | grep "COMBO($name" | awk '{print $4}')" |\
			awk '{ print substr( $0, 1, length($0)-2 ) }'
	done
